name: Dockerize and Deploy to GCP VM

on:
  push:
    branches:
      - main

env:
  GKE_PROJECT: coinmarketcap
  IMAGE: gcr.io/coinmarketcap/trading-platform
  DOCKER_IMAGE_TAG: trading-platform-${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
  
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
  
    - name: Setup GCP CLI
      uses: google-github-actions/setup-gcloud@v0
      with:
        version: '290.0.1'
        project_id: ${{ secrets.GCE_PROJECT }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
  

    - name: Build Docker Image
      run: |
        docker build -t gcr.io/${{ secrets.GCE_PROJECT }}/trading-platform:latest .

    - name: Push Docker Image to GCR
      run: |
        gcloud auth configure-docker
        docker tag ${{env.IMAGE}} ${{env.IMAGE}}:${{env.DOCKER_IMAGE_TAG}}
        docker push ${{env.IMAGE}}:${{env.DOCKER_IMAGE_TAG}}
        docker push gcr.io/${{ secrets.GCE_PROJECT }}/trading-platform:latest

    - name: Deploy Docker Image on GCP VM
      env:
        SSH_PRIVATE_KEY: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
      run: |
        ssh -o StrictHostKeyChecking=no -i <(echo "$SSH_PRIVATE_KEY") username@$(gcloud compute instances describe ${{ secrets.GCP_VM_NAME }} --zone=${{ secrets.GCE_INSTANCE_ZONE }} --format="get(networkInterfaces[0].accessConfigs[0].natIP)") <<EOF
          docker pull gcr.io/${{ secrets.GCE_PROJECT }}/trading-platform:latest
          docker run -d -p 3000:3000 gcr.io/${{ secrets.GCE_PROJECT }}/trading-platform:latest
        EOF
