name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'


    - name: Setup GCP CLI
      uses: google-github-actions/setup-gcloud@v0
      with:
        version: '290.0.1'
        project_id: ${{ secrets.GCE_PROJECT }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Get VM IP
      run: |
        IP=$(gcloud compute instances describe ${{ secrets.GCE_INSTANCE }} --zone=${{ secrets.GCE_INSTANCE_ZONE }} --format="get(networkInterfaces[0].accessConfigs[0].natIP)")
        echo "VM_IP=$IP" >> $GITHUB_ENV

    - name: Deploy to GCP VM
      env:
        PRIVATE_KEY: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
        HOST: $VM_IP
        USER: ${{ secrets.VM_USERNAME }}
        PATH: '~/repos/trading-platform'
      run: |
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        scp -o StrictHostKeyChecking=no -i private_key.pem -r . $USER@$HOST:$PATH
        ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST <<EOF
          cd $PATH
          yarn install
          yarn ts-node src/RSITrackerProcess.ts
        EOF
